Repository Int-Byte4/WizBuddyFront, pull requests merged in 2024-09, with the labels that each got.

#1 ✨ 기능 추가: LoginPage추가
  wizbuddy_front/.gitignore
  wizbuddy_front/.vscode/extensions.json
  wizbuddy_front/README.md
  wizbuddy_front/index.html
  wizbuddy_front/jsconfig.json
  wizbuddy_front/package-lock.json
  wizbuddy_front/package.json
  wizbuddy_front/public/favicon.ico
  wizbuddy_front/src/App.vue
  wizbuddy_front/src/assets/icons/Profile.svg
  wizbuddy_front/src/assets/icons/wizbuddy_logo.svg
  wizbuddy_front/src/assets/icons/로그인.svg
  wizbuddy_front/src/assets/icons/카카오_로그인.svg
  wizbuddy_front/src/assets/icons/큰 아이콘 부분.png
  wizbuddy_front/src/components/AppFooter.vue
  wizbuddy_front/src/components/AppHeader.vue
  wizbuddy_front/src/main.js
  wizbuddy_front/src/router/router.js
  wizbuddy_front/src/views/LoginPage.vue
  wizbuddy_front/src/views/MainPage.vue
  wizbuddy_front/vite.config.js
Labels: enhancement

#2 매장에 들어간 후의 라우팅되는 화면 5가지와 header 추가
  LICENSE
  wizbuddy_front/package-lock.json
  wizbuddy_front/package.json
  wizbuddy_front/src/App.vue
  wizbuddy_front/src/assets/css/style.css
  wizbuddy_front/src/components/AppHeaderInShop.vue
  wizbuddy_front/src/views/InShopPage.vue
Labels: enhancement

#6 ✨ 기능 추가: SignupPage 추가 및 assets 폴더 구조 변경
  wizbuddy_front/src/App.vue
  wizbuddy_front/src/assets/icons/user/로그인.svg
  wizbuddy_front/src/assets/icons/user/카카오_로그인.svg
  wizbuddy_front/src/assets/icons/user/큰 아이콘 부분.png
  wizbuddy_front/src/components/AppHeader.vue
  wizbuddy_front/src/router/router.js
  wizbuddy_front/src/views/LoginPage.vue
  wizbuddy_front/src/views/SignupPage.vue
Labels: enhancement

#7 ✨ 기능 추가: taskMainPage, InsertPage, TaskMain.vue 생성 및 추가, 리다이렉트 로직 구현
  wizbuddy_front/.vite/deps_temp_dd0e6620/package.json
  wizbuddy_front/src/App.vue
  wizbuddy_front/src/components/checklist/TaskMain.vue
  wizbuddy_front/src/router/router.js
  wizbuddy_front/src/views/checklist/TaskInsertPage.vue
  wizbuddy_front/src/views/checklist/TaskMainPage.vue
Labels: bug, enhancement

#8 스케줄 메인화면 추가 및 AppHeader, AppFooter 일부 수정
  wizbuddy_front/package-lock.json
  wizbuddy_front/src/App.vue
  wizbuddy_front/src/components/AppFooter.vue
  wizbuddy_front/src/components/AppHeaderInShop.vue
  wizbuddy_front/src/router/router.js
  wizbuddy_front/src/views/InShopPage.vue
  wizbuddy_front/src/views/ScheduleMainPage.vue
Labels: enhancement

#16 ♻ 코드 수정: AppHeader.vue 수정 및 LoginPage, SignupPage 화면 설정
  wizbuddy_front/src/App.vue
  wizbuddy_front/src/components/AppHeader.vue
  wizbuddy_front/src/views/LoginPage.vue
  wizbuddy_front/src/views/SignupPage.vue
Labels: enhancement

#20 ♻ 코드 수정: App.vue 수정
  wizbuddy_front/src/App.vue
  wizbuddy_front/src/router/router.js
Labels: bug

#21 ✨ 기능 추가 : 달력 컨테이너 수정 및 패키지 이동
  wizbuddy_front/package-lock.json
  wizbuddy_front/src/App.vue
  wizbuddy_front/src/assets/css/schedule/Main.css
  wizbuddy_front/src/components/AppFooter.vue
  wizbuddy_front/src/components/AppHeaderInShop.vue
  wizbuddy_front/src/components/schedule/Main.vue
  wizbuddy_front/src/router/router.js
Labels: enhancement

#23 ♻️ 코드 수정: App.vue 주석처리/AppHeader.vue v-if추가
  wizbuddy_front/src/App.vue
  wizbuddy_front/src/components/AppHeader.vue
Labels: bug

#26 ♻️ 코드 수정: 패키지 구조 수정 2번째
  wizbuddy_front/src/App.vue
  wizbuddy_front/src/router/router.js
  wizbuddy_front/src/router/schedule.js
Labels: enhancement

#27 ✨ 기능 추가: SideMenu.vue, UserProfileMenu.vue 추가
  wizbuddy_front/src/assets/icons/default-profile-img.svg
  wizbuddy_front/src/assets/icons/right-profile-calendars-button.svg
  wizbuddy_front/src/assets/icons/right-profile-manual-button.svg
  wizbuddy_front/src/assets/icons/right-profile-notice-button.svg
  wizbuddy_front/src/assets/icons/right-profile-todos-button.svg
  wizbuddy_front/src/assets/icons/right-profile.svg
  wizbuddy_front/src/components/SideMenu.vue
  wizbuddy_front/src/components/UserProfileMenu.vue
  wizbuddy_front/src/router/router.js
  wizbuddy_front/src/views/MainPage.vue
  wizbuddy_front/src/views/user/LoginPage.vue
  wizbuddy_front/src/views/user/MainPage.vue
Labels: enhancement

#28 ✨ 기능 추가 : 근무일정 페이지 탭 컴포넌트 추가 + 일주일 근무일정 조회 페이지 추가
  wizbuddy_front/src/assets/css/schedule/FindAllSchedules.css
  wizbuddy_front/src/assets/css/schedule/Main.css
  wizbuddy_front/src/components/ScheduleTab.vue
  wizbuddy_front/src/components/schedule/FindAllSchedules.vue
  wizbuddy_front/src/components/schedule/Main.vue
  wizbuddy_front/src/router/router.js
  wizbuddy_front/src/router/schedule.js
Labels: enhancement

#29 ✨ 기능 추가 : 근무일정 일주일 근무일정 주차 변경 시 변동 추가
  wizbuddy_front/src/assets/css/schedule/FindAllSchedules.css
  wizbuddy_front/src/assets/css/schedule/Main.css
  wizbuddy_front/src/components/schedule/FindAllSchedules.vue
  wizbuddy_front/src/components/schedule/Main.vue
Labels: enhancement

#30 ✨ 기능 추가 : 스케줄 직원 등록 모달 기능 추가
  wizbuddy_front/src/assets/css/schedule/Main.css
  wizbuddy_front/src/components/schedule/EmployerSideMenu.vue
  wizbuddy_front/src/components/schedule/FindAllSchedules.vue
  wizbuddy_front/src/components/schedule/Main.vue
  wizbuddy_front/src/components/schedule/RegisterModal.vue
  wizbuddy_front/src/components/schedule/ScheduleTab.vue
  wizbuddy_front/src/router/schedule.js
Labels: enhancement

#31 ✨ 기능 수정 : 스케줄 등록 모달 기능 추가
  wizbuddy_front/src/assets/css/schedule/Main.css
  wizbuddy_front/src/components/schedule/EmployerSideMenu.vue
  wizbuddy_front/src/components/schedule/Main.vue
  wizbuddy_front/src/components/schedule/ScheduleRegisterModal.vue
Labels: enhancement

#32 기능추가: db.json / 로그인 기능 추가 및 css 변경
  wizbuddy_front/db.json
  wizbuddy_front/src/assets/icons/shop/store-icon.svg
  wizbuddy_front/src/components/SideMenu.vue
  wizbuddy_front/src/components/shop/ShopMenu.vue
  wizbuddy_front/src/router/checklist.js
  wizbuddy_front/src/router/manualBoard.js
  wizbuddy_front/src/router/router.js
  wizbuddy_front/src/router/schedule.js
  wizbuddy_front/src/router/task.js
  wizbuddy_front/src/views/user/LoginPage.vue
  wizbuddy_front/src/views/user/MainPage.vue
  wizbuddy_front/src/views/user/SignupPage.vue
Labels: enhancement

#33 ✨ 기능 추가 : 스케줄에 직원 등록 모달 추가
  wizbuddy_front/src/assets/css/schedule/ScheduleRegisterPage.css
  wizbuddy_front/src/components/schedule/EmployeeRegisterModal.vue
  wizbuddy_front/src/components/schedule/EmployerSideMenu.vue
  wizbuddy_front/src/components/schedule/ScheduleRegisterPage.vue
  wizbuddy_front/src/router/schedule.js
Labels: enhancement

#35 ✨ 기능 추가: 매뉴얼 게시글 상세 조회 화면 추가 및 라우터 설정
  wizbuddy_front/src/assets/icons/left-arrow.svg
  wizbuddy_front/src/assets/icons/right-arrow.svg
  wizbuddy_front/src/components/board/BoardBackground.vue
  wizbuddy_front/src/components/board/BoardItem.vue
  wizbuddy_front/src/components/board/BoardTable.vue
  wizbuddy_front/src/components/board/ManualPostDetail.vue
  wizbuddy_front/src/components/board/NoticePostDetail.vue
  wizbuddy_front/src/router/manualBoard.js
  wizbuddy_front/src/router/noticeBoard.js
  wizbuddy_front/src/router/router.js
  wizbuddy_front/src/views/board/ManualPost.vue
  wizbuddy_front/src/views/board/NoticeBoard.vue
Labels: enhancement

#37 ✨ 기능 추가: 로그인/회원가입 기능 추가 및 수정
  wizbuddy_front/db.json
  wizbuddy_front/src/components/UserProfileMenu.vue
  wizbuddy_front/src/views/user/LoginPage.vue
  wizbuddy_front/src/views/user/SignupPage.vue
Labels: enhancement

#38 스케줄 - 단 건 조회 (수정으로 이어질 예정), 삭제 화면, 직원 등록 화면 구현
  wizbuddy_front/src/assets/css/schedule/DeletePage.css
  wizbuddy_front/src/assets/css/schedule/FindAllSchedules.css
  wizbuddy_front/src/assets/css/schedule/Main.css
  wizbuddy_front/src/assets/css/schedule/ScheduleRegisterPage.css
  wizbuddy_front/src/components/schedule/DeletePage.vue
  wizbuddy_front/src/components/schedule/Main.vue
  wizbuddy_front/src/components/schedule/RegisterPage.vue
  wizbuddy_front/src/components/schedule/modal/DeleteModal.vue
  wizbuddy_front/src/components/schedule/modal/ScheduleInfoModal.vue
  wizbuddy_front/src/components/schedule/modal/ScheduleInfoModalForDelete.vue
Labels: enhancement

#39 ✨ 기능 추가 / 수정: checklist side menu의 등록 버튼 로직 구현
  wizbuddy_front/src/components/checklist/ChecklistSideMenu.vue
  wizbuddy_front/src/components/checklist/modal/ChecklistDetailModal.vue
  wizbuddy_front/src/components/checklist/modal/ChecklistInsertModal.vue
  wizbuddy_front/src/components/checklist/modal/NonFixedTaskModal.vue
  wizbuddy_front/src/components/task/TaskItem.vue
  wizbuddy_front/src/components/task/TaskSideMenu.vue
  wizbuddy_front/src/components/task/TaskTab.vue
  wizbuddy_front/src/router/checklist.js
  wizbuddy_front/src/views/checklist/ChecklistListPage.vue
  wizbuddy_front/src/views/task/TaskListPage.vue
Labels: enhancement

#49 ✨ 기능 추가 : 스케줄 - 스케줄 조회 후 수정 버튼으로 이어지는 수정 화면 라우터 추가
  wizbuddy_front/src/assets/css/schedule/EditPage.css
  wizbuddy_front/src/components/schedule/EditPage.vue
  wizbuddy_front/src/components/schedule/modal/ScheduleInfoModal.vue
  wizbuddy_front/src/router/schedule.js
Labels: enhancement

#50 ✨ 기능 수정: UserProfileMenu, AppHeader 기능 수정
  wizbuddy_front/db.json
  wizbuddy_front/src/components/AppHeader.vue
  wizbuddy_front/src/components/UserProfileMenu.vue
  wizbuddy_front/src/components/shop/ShopMenu.vue
  wizbuddy_front/src/views/user/LoginPage.vue
Labels: enhancement

#51 ✨ 기능 추가 / 수정: checklist 관련 curd 기능 구현
  wizbuddy_front/src/components/checklist/ChecklistItem.vue
  wizbuddy_front/src/components/checklist/ChecklistSideMenu.vue
  wizbuddy_front/src/components/checklist/modal/ChecklistEditModal.vue
  wizbuddy_front/src/components/checklist/modal/FixedTaskModal.vue
  wizbuddy_front/src/views/checklist/ChecklistListPage.vue
Labels: enhancement

#52 ♻ 코드 수정: AppHeader 코드 수정
  wizbuddy_front/src/components/AppHeader.vue
  wizbuddy_front/src/components/shop/ShopMenu.vue
  wizbuddy_front/src/views/user/LoginPage.vue
  wizbuddy_front/src/views/user/MainPage.vue
Labels: fix

#53 ♻️ 코드 수정: 폴더 구조 전체적으로 변경
  wizbuddy_front/src/assets/css/schedule/DeletePage.css
  wizbuddy_front/src/assets/css/schedule/Main.css
  wizbuddy_front/src/assets/css/schedule/RegisterPage.css
  wizbuddy_front/src/assets/css/schedule/ScheduleCalendar.css
  wizbuddy_front/src/assets/css/schedule/WeeklyScheduleContainer.css
  wizbuddy_front/src/components/schedule/DeletePage.vue
  wizbuddy_front/src/components/schedule/FindAllSchedules.vue
  wizbuddy_front/src/components/schedule/ScheduleCalendar.vue
  wizbuddy_front/src/components/schedule/WeeklyScheduleContainer.vue
  wizbuddy_front/src/router/schedule.js
  wizbuddy_front/src/views/schedule/DeletePage.vue
  wizbuddy_front/src/views/schedule/EditPage.vue
  wizbuddy_front/src/views/schedule/Main.vue
  wizbuddy_front/src/views/schedule/RegisterPage.vue
  wizbuddy_front/src/views/schedule/WeeklySchedule.vue
Labels: fix

#54 ♻ 코드 수정: MainPage.vue,SideMenu.vue 코드 수정
  wizbuddy_front/src/components/LeftSideMenu.vue
  wizbuddy_front/src/components/LeftTab.vue
  wizbuddy_front/src/components/SideMenu.vue
  wizbuddy_front/src/components/shop/ShopMenu.vue
Labels: enhancement

#56 ✨ 기능 추가: 게시글 작성 화면 구현 및 라우터 설정, 상세 조회 좋아요 기능 구현
  wizbuddy_front/src/components/board/BoardBackground.vue
  wizbuddy_front/src/components/board/BoardItem.vue
  wizbuddy_front/src/components/board/ManualPostDetail.vue
  wizbuddy_front/src/components/board/NoticePostDetail.vue
  wizbuddy_front/src/components/board/PostCreate.vue
  wizbuddy_front/src/router/manualBoard.js
  wizbuddy_front/src/router/noticeBoard.js
Labels: enhancement

#57 ✨ 기능 추가 / 수정: checklist, task service db.json과 연동 완료
  wizbuddy_front/db.json
  wizbuddy_front/src/components/checklist/ChecklistDetail.vue
  wizbuddy_front/src/components/checklist/ChecklistForm.vue
  wizbuddy_front/src/components/checklist/ChecklistSideMenu.vue
  wizbuddy_front/src/components/checklist/modal/ChecklistDetailModal.vue
  wizbuddy_front/src/components/checklist/modal/ChecklistEditModal.vue
  wizbuddy_front/src/components/checklist/modal/ChecklistInsertModal.vue
  wizbuddy_front/src/components/checklist/modal/FixedTaskModal.vue
  wizbuddy_front/src/components/checklist/modal/NonFixedTaskModal.vue
  wizbuddy_front/src/components/task/TaskSideMenu.vue
  wizbuddy_front/src/router/checklist.js
  wizbuddy_front/src/views/checklist/ChecklistCreatePage.vue
  wizbuddy_front/src/views/checklist/ChecklistDetailPage.vue
  wizbuddy_front/src/views/checklist/ChecklistEditPage.vue
  wizbuddy_front/src/views/checklist/ChecklistListPage.vue
  wizbuddy_front/src/views/task/TaskCreatePage.vue
  wizbuddy_front/src/views/task/TaskDetailPage.vue
  wizbuddy_front/src/views/task/TaskEditPage.vue
  wizbuddy_front/src/views/task/TaskListPage.vue
Labels: enhancement, fix

#58 ✨ 기능 추가 : 스케줄 메인화면, 조회, 수정 json-server 연동 추가
  wizbuddy_front/db.json
  wizbuddy_front/package-lock.json
  wizbuddy_front/package.json
  wizbuddy_front/src/assets/css/schedule/ScheduleCalendar.css
  wizbuddy_front/src/components/SideMenu.vue
  wizbuddy_front/src/components/schedule/ScheduleCalendar.vue
  wizbuddy_front/src/components/schedule/modal/ScheduleInfoModal.vue
  wizbuddy_front/src/views/schedule/EditPage.vue
  wizbuddy_front/src/views/schedule/Main.vue
Labels: enhancement

#59 ✨ 기능 추가 / 수정: task form 유효성 검사 및 checklist 데이터 전송
  wizbuddy_front/db.json
  wizbuddy_front/src/components/checklist/modal/ChecklistEditModal.vue
  wizbuddy_front/src/components/checklist/modal/FixedTaskModal.vue
  wizbuddy_front/src/components/checklist/modal/NonFixedTaskModal.vue
  wizbuddy_front/src/components/task/TaskForm.vue
  wizbuddy_front/src/router/checklist.js
  wizbuddy_front/src/views/checklist/ChecklistListPage.vue
  wizbuddy_front/src/views/checklist/ChecklistPastPage.vue
  wizbuddy_front/src/views/task/TaskCreatePage.vue
Labels: bug, enhancement, fix

#75 ✨ 기능 추가 : 대타게시판 경로 및 이동 기능 추가
  wizbuddy_front/src/assets/icons/board/avatar.svg
  wizbuddy_front/src/assets/icons/board/commentimg.svg
  wizbuddy_front/src/components/board/BoardBackground.vue
  wizbuddy_front/src/components/board/BoardItem.vue
  wizbuddy_front/src/components/board/BoardTable.vue
  wizbuddy_front/src/components/board/CommentCount.vue
  wizbuddy_front/src/components/board/SubsPostDetail.vue
  wizbuddy_front/src/components/board/SubsRegister.vue
  wizbuddy_front/src/router/manualBoard.js
  wizbuddy_front/src/router/noticeBoard.js
  wizbuddy_front/src/router/router.js
  wizbuddy_front/src/router/subsBoard.js
  wizbuddy_front/src/router/welcome.js
  wizbuddy_front/src/views/board/SubsBoard.vue
  wizbuddy_front/src/views/board/SubsPost.vue
  wizbuddy_front/src/views/board/SubsRegist.vue
Labels: enhancement

#83 ✨ 기능 추가 : 일주일 근무일정에서 저장된 스케줄 조회 기능 추가
  wizbuddy_front/src/assets/css/schedule/WeeklyScheduleContainer.css
  wizbuddy_front/src/components/schedule/WeeklyScheduleContainer.vue
Labels: enhancement

#88 기능 추가, 파일 구조 변경
  wizbuddy_front/db.json
  wizbuddy_front/src/components/LeftSideMenu.vue
  wizbuddy_front/src/components/SideMenu.vue
  wizbuddy_front/src/components/UserProfileMenu.vue
  wizbuddy_front/src/components/shop/Modal.vue
  wizbuddy_front/src/components/shop/ShopMenu.vue
  wizbuddy_front/src/components/shop/modal/InviteModal.vue
  wizbuddy_front/src/components/shop/modal/shopEdit.vue
  wizbuddy_front/src/components/shop/modal/shopRegist.vue
  wizbuddy_front/src/router/router.js
  wizbuddy_front/src/router/shop.js
  wizbuddy_front/src/router/user.js
  wizbuddy_front/src/views/shop/MainPage.vue
  wizbuddy_front/src/views/user/LoginPage.vue
  wizbuddy_front/src/views/user/MainPage.vue
  wizbuddy_front/src/views/user/SignupPage.vue
Labels: enhancement

#91 ✨ 기능 추가: 게시글 수정 기능 json 서버와 연결
  wizbuddy_front/db.json
  wizbuddy_front/src/components/board/ManualPostDetail.vue
  wizbuddy_front/src/components/board/PostEdit.vue
Labels: enhancement

#92 ✨ 기능 추가 : shop과 schedule 연결 완료
  wizbuddy_front/db.json
  wizbuddy_front/src/assets/css/schedule/EditPage.css
  wizbuddy_front/src/components/AppHeader.vue
  wizbuddy_front/src/components/LeftSideMenu.vue
  wizbuddy_front/src/components/LeftTab.vue
  wizbuddy_front/src/components/SideMenu.vue
  wizbuddy_front/src/components/UserProfileMenu.vue
  wizbuddy_front/src/components/schedule/modal/ScheduleInfoModal.vue
  wizbuddy_front/src/components/shop/ShopMenu.vue
  wizbuddy_front/src/views/schedule/DeletePage.vue
  wizbuddy_front/src/views/schedule/EditPage.vue
  wizbuddy_front/src/views/schedule/Main.vue
  wizbuddy_front/src/views/schedule/RegisterPage.vue
  wizbuddy_front/src/views/shop/MainPage.vue
  wizbuddy_front/src/views/user/LoginPage.vue
Labels: enhancement

#94 ✨ 기능 추가 : 대타게시판 댓글 수 기능 추가
  wizbuddy_front/db.json
  wizbuddy_front/src/assets/icons/board/avater4.svg
  wizbuddy_front/src/assets/icons/board/avater5.svg
  wizbuddy_front/src/components/LeftSideMenu.vue
  wizbuddy_front/src/components/board/BoardItem.vue
  wizbuddy_front/src/components/board/BoardTable.vue
  wizbuddy_front/src/components/board/CommentCount.vue
  wizbuddy_front/src/components/board/SubsPostDetail.vue
  wizbuddy_front/src/components/board/SubsRegister.vue
Labels: enhancement

#95 로컬스토리지 사용으로 스케줄 추가
  wizbuddy_front/db.json
  wizbuddy_front/src/components/AppHeader.vue
  wizbuddy_front/src/components/LeftTab.vue
  wizbuddy_front/src/components/schedule/WeeklyScheduleContainer.vue
  wizbuddy_front/src/components/schedule/modal/ScheduleInfoModal.vue
  wizbuddy_front/src/components/schedule/modal/ScheduleRegisterModal.vue
  wizbuddy_front/src/components/shop/ShopMenu.vue
  wizbuddy_front/src/views/schedule/EditPage.vue
  wizbuddy_front/src/views/schedule/Main.vue
Labels: enhancement

#96 ✨ 기능 추가: 글쓰기, 게시글 수정, 삭제 json 서버 연결
  wizbuddy_front/db.json
  wizbuddy_front/src/components/DeleteModal.vue
  wizbuddy_front/src/components/board/BoardTable.vue
  wizbuddy_front/src/components/board/ManualPostDetail.vue
  wizbuddy_front/src/components/board/NoticePostDetail.vue
  wizbuddy_front/src/components/board/PostCreate.vue
  wizbuddy_front/src/components/board/PostEdit.vue
  wizbuddy_front/src/router/noticeBoard.js
  wizbuddy_front/src/views/schedule/DeletePage.vue
Labels: enhancement

#97 ✨ 기능 추가 / 수정: task, checklist 최종 수정
  wizbuddy_front/db.json
  wizbuddy_front/src/components/checklist/modal/ChecklistDetailModal.vue
  wizbuddy_front/src/components/checklist/modal/ChecklistInsertModal.vue
  wizbuddy_front/src/views/checklist/ChecklistListPage.vue
  wizbuddy_front/src/views/task/TaskDetailPage.vue
  wizbuddy_front/src/views/task/TaskEditPage.vue
  wizbuddy_front/src/views/task/TaskListPage.vue
Labels: bug, enhancement, fix

#99 ✨ 기능 추가: 게시글 작성 시 작성시간 등록 기능 추가
  wizbuddy_front/db.json
  wizbuddy_front/src/components/board/PostCreate.vue
Labels: enhancement

#100 ♻️ 코드 수정: 버튼 css 수정 및 db.json 수정
  wizbuddy_front/db.json
  wizbuddy_front/src/components/board/BoardTable.vue
Labels: enhancement

#101 ♻️ 코드 수정: 다시 로컬스토리지 적용 전으로 수정
  wizbuddy_front/src/components/AppHeader.vue
  wizbuddy_front/src/components/LeftSideMenu.vue
  wizbuddy_front/src/components/LeftTab.vue
  wizbuddy_front/src/views/schedule/EditPage.vue
  wizbuddy_front/src/views/schedule/Main.vue
Labels: fix

#102 ♻️ 코드 수정: 대타게시판 db.json 데이터 수정, 대타게시판 게시글이 제대로 로딩되지 않는 오류 수정
  wizbuddy_front/db.json
  wizbuddy_front/src/components/board/BoardTable.vue
Labels: fix
